### ISSUE TITLE
Where can I find a ESP32 with a connected RS485 

### ISSUE THREAD

**Issue by the-dbp** [jnicolson/twc-controller#5]
I have tried googling and looking it up on banggood and aliexpress with no luck can you link a board?

**Comment by jnicolson** [comment]
Hi,
I'm actually unsure - a quick search and I also couldn't find any pre-built boards.  For my deployment I custom built a board which included an RS485 transceiver.  If you are looking at using off the shelf parts then I could only suggest a separate RS485 board (maybe something like this - untested but should work https://www.aliexpress.com/item/1005001621746811.html) 

It just needs a standard RS485 transceiver, only thing to be careful of is powering it (whether the ESP32 board you're using outputs 5V or 3.3V and then what the RS485 module expects)

**Comment by the-dbp** [comment]
Ok!

**Comment by the-dbp** [comment]
Ok!
